import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { errorText, money, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, CirclePlus, GraduationCap, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";
export default function Exams() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.exams.list.useQuery(); const invalidate = () => Promise.all([utils.exams.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.coins.ledger.invalidate(), utils.achievements.list.invalidate()]); if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; return <div><PageHeader title="الامتحانات" description="سجّل النتائج، ثم احصل على تقدير فهم مدعوم بالذكاء الاصطناعي. الاستيعاب لا يُدخل يدويًا." action={{ label: "امتحان جديد", onClick: () => document.getElementById("exam-trigger")?.click() }} /><CreateExam onDone={invalidate} />{!data?.length ? <EmptyState title="لا توجد امتحانات مسجلة" description="أضف امتحانًا أو اختبارًا قصيرًا لتبدأ بناء مؤشر الاستيعاب." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(item => <ExamCard key={item.exam.id} item={item} onDone={invalidate} />)}</div>}</div>; }
function ExamCard({ item, onDone }: { item: any; onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [total, setTotal] = useState("10"), [correct, setCorrect] = useState("0"), [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("medium"), [result, setResult] = useState<any>(null); const mutation = trpc.exams.completeAttempt.useMutation({ onSuccess: async r => { setResult(r); toast.success(`تم تسجيل النتيجة: ${r.score}% — الاستيعاب ${r.comprehensionScore}%`); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <div className="surface p-5"><div className="mb-5 flex items-start justify-between"><span className="metric-icon bg-sky-100 text-sky-700"><GraduationCap /></span><Badge variant="secondary">{item.subject || "بدون مادة"}</Badge></div><h2 className="font-bold">{item.exam.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.exam.scheduledAt ? `موعده ${shortDate.format(new Date(item.exam.scheduledAt))}` : "اختبار مرن"}</p>{result && <div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-primary/5 p-3 text-center"><div><p className="text-xs text-muted-foreground">النتيجة</p><p className="font-[Manrope] text-xl font-extrabold text-primary">{result.score}%</p></div><div><p className="text-xs text-muted-foreground">الاستيعاب</p><p className="font-[Manrope] text-xl font-extrabold text-primary">{result.comprehensionScore}%</p></div></div>}<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="mt-5 w-full"><BrainCircuit />تسجيل محاولة +15</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>تسجيل محاولة: {item.exam.title}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3"><Input type="number" min="1" value={total} onChange={e => setTotal(e.target.value)} placeholder="عدد الأسئلة" /><Input type="number" min="0" value={correct} onChange={e => setCorrect(e.target.value)} placeholder="الإجابات الصحيحة" /></div><select value={difficulty} onChange={e => setDifficulty(e.target.value as any)} className="h-10 rounded-md border bg-background px-3"><option value="easy">سهل</option><option value="medium">متوسط</option><option value="hard">صعب</option></select><Input placeholder="موضوعات أخطأت بها، مفصولة بفواصل" id={`topics-${item.exam.id}`} /><DialogFooter><Button disabled={mutation.isPending} onClick={() => { const topics = (document.getElementById(`topics-${item.exam.id}`) as HTMLInputElement)?.value.split(",").map(x => x.trim()).filter(Boolean) ?? []; mutation.mutate({ examId: item.exam.id, totalQuestions: Number(total), correctAnswers: Number(correct), difficulty, missedTopics: topics }); }}>حلل الاستيعاب<BrainCircuit /></Button></DialogFooter></DialogContent></Dialog></div>; }
function CreateExam({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [date, setDate] = useState(""); const mutation = trpc.exams.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الامتحان."); setOpen(false); setTitle(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="exam-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>امتحان جديد</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: اختبار الجبر الأسبوعي" /><Input type="date" value={date} onChange={e => setDate(e.target.value)} /><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title, scheduledAt: date ? new Date(`${date}T12:00:00`) : undefined })}><Plus />إضافة</Button></DialogFooter></DialogContent></Dialog>; }
