import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { errorText, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, CheckCircle2, CirclePlus, GraduationCap, Plus, Sparkles, Target } from "lucide-react";
import { toast } from "sonner";

export default function Exams() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.exams.list.useQuery(); const { data: plan } = trpc.studyPlan.list.useQuery();
  const invalidate = () => Promise.all([utils.exams.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.coins.ledger.invalidate(), utils.achievements.list.invalidate()]);
  if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />;
  return <div><PageHeader title="الامتحانات" description="حدّد الدروس التي يغطيها كل امتحان ليحسب الموقع مدى جاهزيتك من الإكمال والمراجعة الفعليين." action={{ label: "امتحان جديد", onClick: () => document.getElementById("exam-trigger")?.click() }} /><CreateExam plan={plan} onDone={invalidate} />{!data?.length ? <EmptyState title="لا توجد امتحانات مسجلة" description="أضف امتحانًا ثم اختر دروسه لتحصل على تقدير واضح لمدى الجاهزية." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(item => <ExamCard key={item.exam.id} item={item} onDone={invalidate} />)}</div>}</div>;
}

function ExamCard({ item, onDone }: { item: any; onDone: () => Promise<any> }) {
  const [open, setOpen] = useState(false), [total, setTotal] = useState("10"), [correct, setCorrect] = useState("0"), [difficulty, setDifficulty] = useState<"easy" | "medium" | "hard">("medium"), [result, setResult] = useState<any>(null);
  const mutation = trpc.exams.completeAttempt.useMutation({ onSuccess: async r => { setResult(r); toast.success(`تم تسجيل النتيجة: ${r.score}% — الاستيعاب ${r.comprehensionScore}%`); await onDone(); }, onError: e => toast.error(errorText(e)) });
  const readiness = item.readiness; const weak = readiness?.weakLessons ?? [];
  return <div className="surface p-5"><div className="mb-5 flex items-start justify-between"><span className="metric-icon bg-sky-100 text-sky-700"><GraduationCap /></span><Badge variant="secondary">{item.subject || "امتحان محدد الدروس"}</Badge></div><h2 className="font-bold">{item.exam.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.exam.scheduledAt ? `موعده ${shortDate.format(new Date(item.exam.scheduledAt))}` : "اختبار مرن"}</p>
    <div className="mt-4 rounded-xl bg-primary/5 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Target className="size-4 text-primary" /><p className="text-sm font-bold">مدى جاهزيتك</p></div><b className="font-[Manrope] text-2xl text-primary">{readiness?.score ?? 0}%</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-primary/10"><div className="h-full rounded-full bg-primary transition-[width]" style={{ width: `${readiness?.score ?? 0}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{readiness?.level ?? "أضف الدروس أولًا"} · مكتمل {readiness?.completed ?? 0}/{item.lessons?.length ?? 0} · مُراجع {readiness?.reviewed ?? 0}/{item.lessons?.length ?? 0}</p></div>
    {item.lessons?.length ? <div className="mt-4"><p className="mb-2 text-xs font-bold text-muted-foreground">دروس الامتحان ({item.lessons.length})</p><div className="space-y-2">{item.lessons.slice(0, 4).map((lesson: any) => <div key={`${lesson.subjectTitle}-${lesson.title}`} className="flex items-center justify-between gap-2 text-xs"><span className="truncate">{lesson.title}</span><span className={lesson.status === "completed" && lesson.lastReviewedAt ? "text-emerald-600" : "text-amber-600"}>{lesson.status === "completed" && lesson.lastReviewedAt ? "مكتمل ومراجع" : lesson.status === "completed" ? "يحتاج مراجعة" : "غير مكتمل"}</span></div>)}</div>{weak.length > 0 && <p className="mt-3 text-xs text-amber-700">ركّز قبل الامتحان على: {weak.slice(0, 2).map((lesson: any) => lesson.title).join("، ")}{weak.length > 2 ? "…" : ""}</p>}</div> : <p className="mt-4 rounded-xl border border-dashed p-3 text-xs text-muted-foreground">هذا الامتحان لم تُضف له دروس بعد، لذلك لا يمكن تقدير الجاهزية بدقة.</p>}
    {result && <div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-primary/5 p-3 text-center"><div><p className="text-xs text-muted-foreground">النتيجة</p><p className="font-[Manrope] text-xl font-extrabold text-primary">{result.score}%</p></div><div><p className="text-xs text-muted-foreground">الاستيعاب</p><p className="font-[Manrope] text-xl font-extrabold text-primary">{result.comprehensionScore}%</p></div></div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="mt-5 w-full"><BrainCircuit />تسجيل محاولة +15</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>تسجيل محاولة: {item.exam.title}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3"><Input type="number" min="1" value={total} onChange={e => setTotal(e.target.value)} placeholder="عدد الأسئلة" /><Input type="number" min="0" value={correct} onChange={e => setCorrect(e.target.value)} placeholder="الإجابات الصحيحة" /></div><select value={difficulty} onChange={e => setDifficulty(e.target.value as any)} className="h-10 rounded-md border bg-background px-3"><option value="easy">سهل</option><option value="medium">متوسط</option><option value="hard">صعب</option></select><Input placeholder="موضوعات أخطأت بها، مفصولة بفواصل" id={`topics-${item.exam.id}`} /><DialogFooter><Button disabled={mutation.isPending} onClick={() => { const topics = (document.getElementById(`topics-${item.exam.id}`) as HTMLInputElement)?.value.split(",").map(x => x.trim()).filter(Boolean) ?? []; mutation.mutate({ examId: item.exam.id, totalQuestions: Number(total), correctAnswers: Number(correct), difficulty, missedTopics: topics }); }}>حلل الاستيعاب<BrainCircuit /></Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function CreateExam({ onDone, plan }: { onDone: () => Promise<any>; plan: any }) {
  const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [date, setDate] = useState(""), [selected, setSelected] = useState<number[]>([]);
  const lessons = useMemo(() => (plan?.rows ?? []).flatMap((row: any) => row.lesson ? [{ id: row.lesson.id, title: row.lesson.title, chapter: row.chapter?.title ?? "", subject: row.subject?.title ?? "" }] : []), [plan]);
  const mutation = trpc.exams.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الامتحان وحساب الجاهزية."); setOpen(false); setTitle(""); setDate(""); setSelected([]); await onDone(); }, onError: e => toast.error(errorText(e)) });
  const toggle = (id: number) => setSelected(items => items.includes(id) ? items.filter(item => item !== id) : [...items, id]);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="exam-trigger" asChild><span /></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>امتحان جديد</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: اختبار الجبر الأسبوعي" /><Input type="date" value={date} onChange={e => setDate(e.target.value)} /><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-bold">الدروس التي سيشملها الامتحان</p><Badge variant="secondary">{selected.length} محدد</Badge></div>{lessons.length ? <div className="max-h-64 space-y-2 overflow-y-auto rounded-xl border p-3">{lessons.map((lesson: any) => <label key={lesson.id} className="flex cursor-pointer items-start gap-3 rounded-lg p-2 hover:bg-muted"><input className="mt-1" type="checkbox" checked={selected.includes(lesson.id)} onChange={() => toggle(lesson.id)} /><span><b className="block text-sm">{lesson.title}</b><span className="text-xs text-muted-foreground">{lesson.subject}{lesson.chapter ? ` · ${lesson.chapter}` : ""}</span></span></label>)}</div> : <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">أضف الدروس إلى خطة المذاكرة أولًا، ثم ستظهر هنا لاختيارها.</p>}</div><p className="text-xs leading-5 text-muted-foreground">الجاهزية = 70% من إكمال الدروس المحددة + 30% من مراجعتها، لذلك لن تُحسب من دروس غير مرتبطة بالامتحان.</p><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title, lessonIds: selected, scheduledAt: date ? new Date(`${date}T12:00:00`) : undefined })}><Plus />إضافة الامتحان</Button></DialogFooter></DialogContent></Dialog>;
}
