import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { completionToast, errorText, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { CalendarClock, CheckCircle2, Pencil, Plus, Target, Trash2 } from "lucide-react";
import { toast } from "sonner";
export default function Goals() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.goals.list.useQuery(); const invalidate = () => Promise.all([utils.goals.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.achievements.list.invalidate()]); if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; return <div><PageHeader title="الأهداف" description="اربط جلساتك اليومية بهدف واضح. Coins تأتي عند إكمال الهدف، لا عند كتابته." action={{ label: "هدف جديد", onClick: () => document.getElementById("goal-trigger")?.click() }} /><CreateGoal onDone={invalidate} />{!data?.length ? <EmptyState title="ما الذي تريد إنجازه في هذه الدورة؟" description="ابدأ بهدف واحد واقعي، ثم حدّث التقدم بصدق حتى يصل إلى 100%." /> : <div className="grid gap-4 lg:grid-cols-2">{data.map(goal => <GoalCard key={goal.id} goal={goal} onDone={invalidate} />)}</div>}</div>; }
function GoalCard({ goal, onDone }: { goal: any; onDone: () => Promise<any> }) { const mutation = trpc.goals.updateProgress.useMutation({ onSuccess: async r => { if (r.completedNow) completionToast(r, 50); else toast.success("تم تحديث التقدم."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const remove = trpc.goals.delete.useMutation({ onSuccess: async () => { toast.success("تم حذف الهدف."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const edit = trpc.goals.update.useMutation({ onSuccess: async () => { toast.success("تم تحديث الهدف."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const [value, setValue] = useState(String(goal.progress)); const complete = goal.status === "completed"; const updateTitle = () => { const title = window.prompt("عنوان الهدف", goal.title); if (title?.trim()) edit.mutate({ goalId: goal.id, title, description: goal.description ?? undefined, deadline: goal.deadline ? new Date(goal.deadline) : undefined }); }; return <div className="surface p-5"><div className="mb-4 flex items-start gap-3"><span className={`metric-icon ${complete ? "bg-emerald-100 text-emerald-700" : "bg-violet-100 text-violet-700"}`}>{complete ? <CheckCircle2 /> : <Target />}</span><div className="min-w-0 flex-1"><h2 className="font-bold">{goal.title}</h2><p className="mt-1 text-sm text-muted-foreground">{goal.description || "بدون وصف"}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="تعديل الهدف" onClick={updateTitle}><Pencil className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="حذف الهدف" disabled={remove.isPending} onClick={() => window.confirm("حذف هذا الهدف؟") && remove.mutate({ goalId: goal.id })}><Trash2 className="size-4 text-rose-600" /></Button></div></div><div className="mb-3 flex items-center justify-between text-sm"><span className="text-muted-foreground">التقدم</span><span className="font-[Manrope] font-bold text-primary">{goal.progress}%</span></div><Progress value={goal.progress} className="h-2.5" /><div className="mt-5 flex flex-wrap items-center gap-2"><Input type="number" min="0" max="100" value={value} onChange={e => setValue(e.target.value)} className="w-24" disabled={complete} /><Button disabled={complete || mutation.isPending} onClick={() => mutation.mutate({ goalId: goal.id, progress: Number(value) })}>{Number(value) >= 100 ? "إكمال +50" : "تحديث"}</Button>{goal.deadline && <span className="mr-auto flex items-center gap-1 text-xs text-muted-foreground"><CalendarClock className="size-3.5" />{shortDate.format(new Date(goal.deadline))}</span>}</div></div>; }
function CreateGoal({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [desc, setDesc] = useState(""), [deadline, setDeadline] = useState(""); const mutation = trpc.goals.create.useMutation({ onSuccess: async () => { toast.success("تم إنشاء الهدف."); setOpen(false); setTitle(""); setDesc(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="goal-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>هدف جديد</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: إتقان الفصل الأول" /><Textarea value={desc} onChange={e => setDesc(e.target.value)} placeholder="لماذا يهمك هذا الهدف؟" /><Input type="date" value={deadline} onChange={e => setDeadline(e.target.value)} /><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title, description: desc || undefined, deadline: deadline ? new Date(`${deadline}T12:00:00`) : undefined })}><Plus />إنشاء الهدف</Button></DialogFooter></DialogContent></Dialog>; }
