import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { completionToast, errorText } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { Check, Flame, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
export default function Habits() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.habits.list.useQuery(); const invalidate = () => Promise.all([utils.habits.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate()]); if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; return <div><PageHeader title="العادات" description="ثبّت سلوكًا صغيرًا كل يوم. لا يمكن الحصول على مكافأة العادة أكثر من مرة في اليوم نفسه." action={{ label: "عادة جديدة", onClick: () => document.getElementById("habit-trigger")?.click() }} /><CreateHabit onDone={invalidate} />{!data?.items.length ? <EmptyState title="ابنِ عادة تخدم أهدافك" description="اختر سلوكًا بسيطًا ومتكررًا، مثل مراجعة عشرين دقيقة أو حل مسألتين." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.items.map(habit => <HabitCard key={habit.id} habit={habit} completed={data.completedIds.includes(habit.id)} onDone={invalidate} />)}</div>}</div>; }
function HabitCard({ habit, completed, onDone }: { habit: any; completed: boolean; onDone: () => Promise<any> }) { const mutation = trpc.habits.complete.useMutation({ onSuccess: async r => { completionToast(r, 10); await onDone(); }, onError: e => toast.error(errorText(e)) }); const remove = trpc.habits.delete.useMutation({ onSuccess: async () => { toast.success("تم حذف العادة."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const edit = trpc.habits.update.useMutation({ onSuccess: async () => { toast.success("تم تحديث العادة."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const updateName = () => { const name = window.prompt("اسم العادة", habit.name); if (name?.trim()) edit.mutate({ habitId: habit.id, name, frequency: habit.frequency, target: habit.target }); }; return <div className="surface p-5"><div className="mb-5 flex items-start justify-between"><div className="metric-icon bg-orange-100 text-orange-700"><Flame /></div><div className="flex items-center gap-1"><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{habit.frequency === "daily" ? "يوميًا" : "أسبوعيًا"}</span><Button size="icon" variant="ghost" aria-label="تعديل العادة" onClick={updateName}><Pencil className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="حذف العادة" disabled={remove.isPending} onClick={() => window.confirm("حذف هذه العادة؟") && remove.mutate({ habitId: habit.id })}><Trash2 className="size-4 text-rose-600" /></Button></div></div><h2 className="font-bold">{habit.name}</h2><p className="mt-1 text-sm text-muted-foreground">الهدف: {habit.target} {habit.target > 1 ? "مرات" : "مرة"}</p><Button className="mt-5 w-full" variant={completed ? "secondary" : "default"} disabled={completed || mutation.isPending} onClick={() => mutation.mutate({ habitId: habit.id })}>{completed ? <><Check />تم اليوم</> : <>إكمال اليوم +10</>}</Button></div>; }
function CreateHabit({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [name, setName] = useState(""), [target, setTarget] = useState("1"); const mutation = trpc.habits.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة العادة."); setOpen(false); setName(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="habit-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>عادة جديدة</DialogTitle></DialogHeader><Input value={name} onChange={e => setName(e.target.value)} placeholder="مثال: مراجعة مفردات الإنجليزية" /><Input type="number" min="1" max="7" value={target} onChange={e => setTarget(e.target.value)} placeholder="الهدف اليومي" /><DialogFooter><Button disabled={!name.trim() || mutation.isPending} onClick={() => mutation.mutate({ name, frequency: "daily", target: Number(target) || 1 })}><Plus />إضافة العادة</Button></DialogFooter></DialogContent></Dialog>; }
