import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { errorText } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, FilePlus2, ListChecks, MessageSquareText, NotebookPen, Plus, Sparkles, WandSparkles } from "lucide-react";
import { Streamdown } from "streamdown";
import { toast } from "sonner";

export default function Notebooks() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.notebooks.list.useQuery(); const [activeId, setActiveId] = useState<number | null>(null);
  const notes = trpc.notebooks.notes.useQuery({ notebookId: activeId ?? 0 }, { enabled: !!activeId }); const invalidate = () => utils.notebooks.list.invalidate(); const invalidateNotes = () => activeId && utils.notebooks.notes.invalidate({ notebookId: activeId });
  if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />;
  return <div><PageHeader title="Notebook AI" description="نظّم موادك في دفاتر وملاحظات، ثم اطلب تلخيصًا أو شرحًا أو اختبارًا مستندًا فقط إلى ما كتبته." action={{ label: "دفتر جديد", onClick: () => document.getElementById("notebook-trigger")?.click() }} />
    <CreateNotebook onDone={invalidate} />
    {!data?.length ? <EmptyState title="أنشئ أول دفتر" description="أنشئ دفترًا لمادة أو مشروع، ثم أضف ملاحظات منظمة تستطيع Notebook AI استخدامها." /> : <div className="grid gap-4 xl:grid-cols-[.32fr_1fr]"><aside className="surface divide-y overflow-hidden">{data.map(row => <button key={row.notebook.id} onClick={() => setActiveId(row.notebook.id)} className={`w-full p-4 text-right transition hover:bg-muted/60 ${activeId === row.notebook.id ? "bg-primary/5" : ""}`}><div className="flex items-center gap-3"><span className="metric-icon bg-primary/10 text-primary"><NotebookPen /></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{row.notebook.title}</p><p className="text-xs text-muted-foreground">{row.noteCount} ملاحظات</p></div></div></button>)}</aside><section>{!activeId ? <div className="surface flex min-h-72 items-center justify-center p-8 text-center text-sm text-muted-foreground">اختر دفترًا لعرض الملاحظات وأدوات الذكاء الاصطناعي.</div> : <div className="space-y-4"><NotebookTools notebookId={activeId} /><div className="surface overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div><p className="font-bold">الملاحظات</p><p className="text-xs text-muted-foreground">{data.find(x => x.notebook.id === activeId)?.notebook.title}</p></div><CreateNote notebookId={activeId} onDone={invalidateNotes} /></div><div className="divide-y">{notes.data?.length ? notes.data.map(note => <article key={note.id} className="p-5"><h2 className="font-bold">{note.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{note.content}</p></article>) : <p className="p-8 text-center text-sm text-muted-foreground">أضف ملاحظة واحدة على الأقل لتفعيل أدوات Notebook AI.</p>}</div></div></div>}</section></div>}</div>;
}

function NotebookTools({ notebookId }: { notebookId: number }) {
  const [result, setResult] = useState<string | null>(null); const [question, setQuestion] = useState(""); const mutation = trpc.notebooks.ai.useMutation({ onSuccess: answer => setResult(typeof answer === "string" ? answer : JSON.stringify(answer)), onError: e => toast.error(errorText(e)) }); const run = (mode: "summary" | "quiz" | "explain" | "question") => mutation.mutate({ notebookId, mode, prompt: mode === "question" ? question : undefined });
  return <section className="surface p-4"><div className="flex flex-wrap items-center gap-2"><span className="metric-icon bg-violet-100 text-violet-700"><Sparkles /></span><div className="ml-auto flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => run("summary")}><ListChecks />تلخيص</Button><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => run("explain")}><BookOpenCheck />شرح</Button><Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => run("quiz")}><WandSparkles />اختبار</Button></div></div><div className="mt-3 flex gap-2"><Input value={question} onChange={e => setQuestion(e.target.value)} placeholder="اسأل Notebook AI عن هذه الملاحظات..." /><Button disabled={!question.trim() || mutation.isPending} onClick={() => run("question")}><MessageSquareText />اسأل</Button></div>{mutation.isPending && <p className="mt-4 text-sm text-muted-foreground">يجري تحليل ملاحظاتك…</p>}{result && <div className="prose prose-sm mt-4 max-w-none rounded-xl bg-muted/55 p-4 text-foreground"><Streamdown>{result}</Streamdown></div>}</section>;
}

function CreateNotebook({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""); const mutation = trpc.notebooks.create.useMutation({ onSuccess: async () => { toast.success("تم إنشاء الدفتر."); setOpen(false); setTitle(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="notebook-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>دفتر جديد</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: فيزياء — الوحدة الأولى" /><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title })}><Plus />إنشاء الدفتر</Button></DialogFooter></DialogContent></Dialog>; }
function CreateNote({ notebookId, onDone }: { notebookId: number; onDone: () => any }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [content, setContent] = useState(""); const mutation = trpc.notebooks.createNote.useMutation({ onSuccess: async () => { toast.success("تم حفظ الملاحظة."); setOpen(false); setTitle(""); setContent(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><FilePlus2 />ملاحظة</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>ملاحظة جديدة</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="عنوان الملاحظة" /><Textarea value={content} onChange={e => setContent(e.target.value)} className="min-h-44" placeholder="اكتب المادة، الملخص، الأمثلة، أو الأسئلة..." /><DialogFooter><Button disabled={!title.trim() || !content.trim() || mutation.isPending} onClick={() => mutation.mutate({ notebookId, title, content })}><Plus />حفظ</Button></DialogFooter></DialogContent></Dialog>; }
