import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { errorText } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, FilePlus2, FileText, ListChecks, MessageSquareText, NotebookPen, Plus, ShieldCheck, Sparkles, UploadCloud, WandSparkles } from "lucide-react";
import { Streamdown } from "streamdown";
import { toast } from "sonner";
import { useLocation } from "wouter";

async function fileAsBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("تعذر قراءة الملف")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }
function fileMime(file: File): "text/plain" | "text/markdown" | "application/pdf" | null { if (file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")) return "application/pdf"; if (file.type === "text/markdown" || /\.(md|markdown)$/i.test(file.name)) return "text/markdown"; if (file.type.startsWith("text/") || /\.(txt|csv)$/i.test(file.name)) return "text/plain"; return null; }

export default function Notebooks() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.notebooks.list.useQuery(); const [activeId, setActiveId] = useState<number | null>(null);
  const notes = trpc.notebooks.notes.useQuery({ notebookId: activeId ?? 0 }, { enabled: !!activeId }); const invalidate = () => utils.notebooks.list.invalidate(); const invalidateNotes = () => activeId && utils.notebooks.notes.invalidate({ notebookId: activeId });
  if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />;
  return <div><PageHeader title="Notebook AI" description="ارفع ملفات مذاكرتك، واسألها أو لخصها أو اعمل منها امتحان. الإجابات مش هتطلع برّه اللي رفعته." action={{ label: "دفتر جديد", onClick: () => document.getElementById("notebook-trigger")?.click() }} />
    <section className="mb-5 rounded-3xl border border-violet-200 bg-gradient-to-l from-violet-50 via-white to-cyan-50 p-5"><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-violet-600 text-white"><ShieldCheck /></span><div><h2 className="font-extrabold">مصدر الإجابة هو ملفاتك وبس</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">ارفع PDF أو TXT أو Markdown حتى 5 MB. لو سؤالك مش موجود في الملفات، Notebook AI هيقولك بصراحة بدل ما يخمّن.</p></div></div></section>
    <CreateNotebook onDone={invalidate} />
    {!data?.length ? <EmptyState title="أنشئ أول دفتر" description="اعمل دفتر لمادة، وبعدها ارفع الملازم أو الملفات اللي عايز تذاكر منها." /> : <div className="grid gap-4 xl:grid-cols-[.32fr_1fr]"><aside className="surface divide-y overflow-hidden">{data.map(row => <button key={row.notebook.id} onClick={() => setActiveId(row.notebook.id)} className={`w-full p-4 text-right transition hover:bg-muted/60 ${activeId === row.notebook.id ? "bg-primary/5" : ""}`}><div className="flex items-center gap-3"><span className="metric-icon bg-primary/10 text-primary"><NotebookPen /></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{row.notebook.title}</p><p className="text-xs text-muted-foreground">{row.noteCount} ملاحظة يدوية</p></div></div></button>)}</aside><section>{!activeId ? <div className="surface flex min-h-72 items-center justify-center p-8 text-center text-sm text-muted-foreground">اختار دفترًا وارفع ملفات المادة.</div> : <div className="space-y-4"><NotebookTools notebookId={activeId} /><div className="surface overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div><p className="font-bold">ملاحظات يدوية — اختيارية</p><p className="text-xs text-muted-foreground">تقدر تضيفها لو حابب، لكن Notebook AI يشتغل بالملفات لوحدها.</p></div><CreateNote notebookId={activeId} onDone={invalidateNotes} /></div><div className="divide-y">{notes.data?.length ? notes.data.map(note => <article key={note.id} className="p-5"><h2 className="font-bold">{note.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{note.content}</p></article>) : <p className="p-8 text-center text-sm text-muted-foreground">مفيش ملاحظات يدوية — ارفع ملف من مربع الملفات فوق وابدأ على طول.</p>}</div></div></div>}</section></div>}</div>;
}

function NotebookTools({ notebookId }: { notebookId: number }) {
  const utils = trpc.useUtils(); const [, setLocation] = useLocation(); const { data: sources = [], isLoading } = trpc.notebooks.sources.useQuery({ notebookId }); const [result, setResult] = useState<string | null>(null); const [question, setQuestion] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const refresh = () => utils.notebooks.sources.invalidate({ notebookId }); const upload = trpc.notebooks.uploadSource.useMutation({ onSuccess: async () => { toast.success("الملف اتحفظ وبقى جاهز للسؤال والتلخيص."); await refresh(); }, onError: e => toast.error(errorText(e)) }); const mutation = trpc.notebooks.ai.useMutation({ onSuccess: answer => setResult(typeof answer === "string" ? answer : JSON.stringify(answer)), onError: e => toast.error(errorText(e)) }); const createQuiz = trpc.notebooks.createQuiz.useMutation({ onSuccess: async () => { await utils.exams.list.invalidate(); toast.success("الامتحان اتحفظ تلقائيًا في صفحة الامتحانات."); setLocation("/exams"); }, onError: e => toast.error(errorText(e)) }); const run = (mode: "summary" | "explain" | "question") => mutation.mutate({ notebookId, mode, prompt: mode === "question" ? question : undefined });
  const selectFile = async (file?: File) => { if (!file) return; const mimeType = fileMime(file); if (!mimeType) { toast.error("ارفع PDF أو TXT أو Markdown فقط."); return; } if (file.size > 5 * 1024 * 1024) { toast.error("حجم الملف لازم يكون 5 MB أو أقل."); return; } try { upload.mutate({ notebookId, fileName: file.name, mimeType, contentBase64: await fileAsBase64(file) }); } catch { toast.error("مش قادر أقرأ الملف ده."); } };
  return <section className="surface p-5"><div className="flex flex-col gap-4 border-b pb-5 md:flex-row md:items-center md:justify-between"><div><p className="flex items-center gap-2 font-bold"><FileText className="size-5 text-primary" />ملفات المصدر</p><p className="mt-1 text-xs text-muted-foreground">{sources.length ? `${sources.length} ملف جاهز للمراجعة` : "ارفع ملفاتك علشان تفعّل Notebook AI"}</p></div><input ref={inputRef} type="file" accept=".pdf,.txt,.md,.markdown,text/plain,text/markdown,application/pdf" className="hidden" onChange={event => selectFile(event.target.files?.[0])} /><Button disabled={upload.isPending} onClick={() => inputRef.current?.click()}><UploadCloud />{upload.isPending ? "جارٍ رفع الملف…" : "ارفع ملف"}</Button></div>{isLoading ? <div className="mt-4 h-16 animate-pulse rounded-xl bg-muted" /> : sources.length ? <div className="mt-4 grid gap-2 md:grid-cols-2">{sources.map(source => <a key={source.id} href={source.storageUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm hover:bg-muted"><FileText className="size-5 text-primary" /><span className="min-w-0 flex-1 truncate font-semibold">{source.fileName}</span><span className="text-xs text-muted-foreground">{source.characterCount ? `${source.characterCount.toLocaleString()} حرف` : "PDF"}{source.isTruncated ? " · مختصر" : ""}</span></a>)}</div> : <p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-muted-foreground">ابدأ برفع ملزمة أو ملف المحاضرة. بعد الرفع تقدر تلخص، تسأل، أو تعمل امتحان من الملف نفسه.</p>}<div className="mt-5 flex flex-wrap items-center gap-2"><span className="metric-icon bg-violet-100 text-violet-700"><Sparkles /></span><Button size="sm" variant="outline" disabled={!sources.length || mutation.isPending} onClick={() => run("summary")}><ListChecks />لخّص الملفات</Button><Button size="sm" variant="outline" disabled={!sources.length || mutation.isPending} onClick={() => run("explain")}><BookOpenCheck />اشرح من الملفات</Button><Button size="sm" variant="outline" disabled={!sources.length || createQuiz.isPending} onClick={() => createQuiz.mutate({ notebookId })}><WandSparkles />{createQuiz.isPending ? "بيتحفظ…" : "اعمل امتحان"}</Button></div><p className="mt-2 text-xs text-muted-foreground">الامتحان بيتحفظ تلقائيًا في صفحة الامتحانات للمراجعة بعد الإنشاء.</p><div className="mt-3 flex gap-2"><Input value={question} onChange={e => setQuestion(e.target.value)} placeholder="اسأل سؤال من ملفاتك..." /><Button disabled={!sources.length || !question.trim() || mutation.isPending} onClick={() => run("question")}><MessageSquareText />اسأل</Button></div>{mutation.isPending && <p className="mt-4 text-sm text-muted-foreground">بيدوّر في الملفات المرفوعة…</p>}{result && <div className="prose prose-sm mt-4 max-w-none rounded-xl bg-muted/55 p-4 text-foreground"><Streamdown>{result}</Streamdown></div>}</section>;
}
function CreateNotebook({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""); const mutation = trpc.notebooks.create.useMutation({ onSuccess: async () => { toast.success("الدفتر اتعمل. ارفع ملفاتك دلوقتي."); setOpen(false); setTitle(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="notebook-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>دفتر جديد</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: فيزياء — الوحدة الأولى" /><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title })}><Plus />إنشاء الدفتر</Button></DialogFooter></DialogContent></Dialog>; }
function CreateNote({ notebookId, onDone }: { notebookId: number; onDone: () => any }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [content, setContent] = useState(""); const mutation = trpc.notebooks.createNote.useMutation({ onSuccess: async () => { toast.success("اتحفظت الملاحظة."); setOpen(false); setTitle(""); setContent(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><FilePlus2 />ملاحظة</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>ملاحظة يدوية</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="عنوان الملاحظة" /><Textarea value={content} onChange={e => setContent(e.target.value)} className="min-h-44" placeholder="إضافة اختيارية بجانب ملفاتك…" /><DialogFooter><Button disabled={!title.trim() || !content.trim() || mutation.isPending} onClick={() => mutation.mutate({ notebookId, title, content })}><Plus />حفظ</Button></DialogFooter></DialogContent></Dialog>; }
