import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { errorText, money, rarityColor, rarityNames, uuid } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { Gift, LockKeyhole, ShoppingBag } from "lucide-react";
import { toast } from "sonner";
const rarities = ["all", "common", "uncommon", "rare", "epic", "legendary", "mythic"];
export default function Rewards() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.rewards.list.useQuery(); const [filter, setFilter] = useState("all"); const items = useMemo(() => (data?.items ?? []).filter(x => filter === "all" || x.rarity === filter), [data, filter]); const purchase = trpc.rewards.purchase.useMutation({ onSuccess: async r => { if (r.purchased) toast.success(`تم شراء ${r.reward}.`); else toast.message("تم تسجيل هذه العملية مسبقًا."); await Promise.all([utils.rewards.list.invalidate(), utils.coins.ledger.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate()]); }, onError: e => toast.error(errorText(e)) }); if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; if (!data) return <EmptyState title="المتجر غير متاح" description="حاول تحديث الصفحة لاحقًا." />; return <div><PageHeader title="الهدايا" description="100 مكافأة واقعية لتحويل التقدم الدراسي إلى حافز ملموس. لا يمكن الشراء عندما يكون الرصيد غير كافٍ." /><div className="surface mb-5 flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="metric-icon bg-amber-100 text-amber-800"><Gift /></span><div><p className="text-xs text-muted-foreground">رصيدك المتاح</p><p className="font-[Manrope] text-2xl font-extrabold text-primary">{money.format(data.coins.balance)} Coins</p></div></div><div className="mr-auto flex flex-wrap gap-1">{rarities.map(x => <button key={x} onClick={() => setFilter(x)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${filter === x ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{x === "all" ? "الكل" : rarityNames[x]}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(reward => { const afford = data.coins.balance >= reward.cost; return <div key={reward.id} className="surface p-4"><div className="mb-4 flex items-start justify-between"><span className="metric-icon bg-primary/10 text-primary"><ShoppingBag /></span><Badge className={rarityColor[reward.rarity]}>{rarityNames[reward.rarity]}</Badge></div><h2 className="font-semibold">{reward.title}</h2><div className="mt-4 flex items-center justify-between"><b className="font-[Manrope] text-primary">{money.format(reward.cost)} Coins</b><Button size="sm" variant={afford ? "default" : "outline"} disabled={!afford || purchase.isPending} onClick={() => purchase.mutate({ rewardId: reward.id, referenceKey: uuid() })}>{afford ? "شراء" : <><LockKeyhole />غير كافٍ</>}</Button></div></div>; })}</div></div>; }
