import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/PageHeader";
import { errorText, money, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { isDirectMedia, youtubeEmbed } from "@/lib/videoSources";
import { CirclePause, CirclePlay, Clock3, ExternalLink, History, PlayCircle, Square, Video, XCircle } from "lucide-react";
import { toast } from "sonner";

function clock(seconds: number) { return `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function StudyVideo() {
  const utils = trpc.useUtils(); const { data: session, isLoading } = trpc.video.current.useQuery(); const { data: history } = trpc.video.history.useQuery(); const [url, setUrl] = useState(""); const [now, setNow] = useState(Date.now()); const video = useRef<HTMLVideoElement>(null); const interval = useRef<number | null>(null);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const invalidate = () => Promise.all([utils.video.current.invalidate(), utils.video.history.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.coins.ledger.invalidate()]);
  const start = trpc.video.start.useMutation({ onSuccess: async () => { setUrl(""); toast.success("تم بدء جلسة الفيديو."); await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const end = trpc.video.end.useMutation({ onSuccess: async () => { toast.success("تم إنهاء جلسة الفيديو."); await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const heartbeat = trpc.video.heartbeat.useMutation({ onSuccess: async r => { if (r.blockCompleted) { toast.success("أحسنت! +25 Coins — بدأت استراحة 15 دقيقة."); video.current?.pause(); } await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const resume = trpc.video.resume.useMutation({ onSuccess: async () => { await invalidate(); video.current?.play().catch(() => undefined); }, onError: e => toast.error(errorText(e)) });
  const send = (active: boolean) => { if (!session) return; heartbeat.mutate({ sessionId: session.id, active, playbackPosition: Math.floor(video.current?.currentTime ?? 0) }); };
  const onPlay = () => { send(true); if (interval.current) clearInterval(interval.current); interval.current = window.setInterval(() => send(true), 60_000); };
  const onPause = () => { if (interval.current) clearInterval(interval.current); interval.current = null; send(false); };
  useEffect(() => () => { if (interval.current) clearInterval(interval.current); }, []);
  const breakRemaining = session?.phase === "break" && session.breakEndsAt ? Math.max(0, Math.ceil((new Date(session.breakEndsAt).getTime() - now) / 1000)) : 0;
  useEffect(() => { if (session?.phase === "break" && breakRemaining === 0 && !resume.isPending) resume.mutate({ sessionId: session.id }); }, [breakRemaining, session?.id, session?.phase]);
  const launch = () => { const clean = url.trim(); if (!youtubeEmbed(clean) && !isDirectMedia(clean)) { toast.error("استخدم رابط YouTube صحيحًا أو رابط ملف فيديو مباشر ينتهي بـ MP4 أو WebM."); return; } start.mutate({ videoUrl: clean }); };
  if (isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-muted" />;
  return <div><PageHeader title="فيديو المذاكرة" description="شغّل فيديو YouTube أو ملف MP4/WebM. احتساب Coins يعمل فقط مع ملفات الفيديو المباشرة لأن تقدم YouTube لا يمكن التحقق منه داخل التطبيق." />
    {!session ? <div className="surface mx-auto max-w-2xl p-6 sm:p-8"><div className="mb-5 flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Video /></div><h2 className="text-xl font-bold">ابدأ دورة فيديو دراسة</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">الصق رابط YouTube للمشاهدة، أو رابط ملف مباشر ينتهي بـ MP4/WebM للمشاهدة مع احتساب التركيز.</p><div className="mt-6 flex gap-2"><Input dir="ltr" value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === "Enter" && launch()} placeholder="YouTube أو https://example.com/lecture.mp4" /><Button disabled={!url || start.isPending} onClick={launch}>ابدأ</Button></div><p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><ExternalLink className="size-3" />روابط صفحات المواقع أو Drive غير المباشرة لا تعمل داخل المشغّل؛ استخدم رابط فيديو مباشر أو YouTube.</p></div> : <div className="grid gap-5 xl:grid-cols-[1fr_.38fr]"><section className="surface overflow-hidden"><Player session={session} video={video} onPlay={onPlay} onPause={onPause} breakRemaining={breakRemaining} onResume={() => resume.mutate({ sessionId: session.id })} /><div className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-semibold">جلسة فيديو نشطة</p><p dir="ltr" className="mt-1 max-w-96 truncate text-xs text-muted-foreground">{session.videoUrl}</p></div><Button size="sm" variant="outline" disabled={end.isPending} onClick={() => end.mutate({ sessionId: session.id })}><Square />إنهاء الجلسة</Button></div></section><VideoSidebar session={session} history={history ?? []} /></div>}
  </div>;
}

function Player({ session, video, onPlay, onPause, breakRemaining, onResume }: { session: any; video: React.RefObject<HTMLVideoElement | null>; onPlay: () => void; onPause: () => void; breakRemaining: number; onResume: () => void }) { const embed = youtubeEmbed(session.videoUrl); if (session.phase === "break") return <div className="relative aspect-video bg-slate-950"><div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center text-white"><CirclePause className="mb-4 size-10 text-amber-300" /><p className="text-sm text-slate-300">فترة استراحة</p><p className="font-[Manrope] text-6xl font-extrabold">{String(Math.floor(breakRemaining / 60)).padStart(2, "0")}:{String(breakRemaining % 60).padStart(2, "0")}</p><Button className="mt-5" onClick={onResume} disabled={breakRemaining > 0}><CirclePlay />استئناف</Button></div></div>; if (embed) return <div className="aspect-video bg-black"><iframe title="فيديو المذاكرة" className="h-full w-full" src={embed} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div>; if (isDirectMedia(session.videoUrl)) return <div className="aspect-video bg-black"><video ref={video} controls className="h-full w-full" src={session.videoUrl} onPlay={onPlay} onPause={onPause} onEnded={onPause}>متصفحك لا يدعم تشغيل الفيديو.</video></div>; return <div className="flex aspect-video flex-col items-center justify-center gap-3 bg-slate-950 p-6 text-center text-white"><XCircle className="size-11 text-rose-300" /><p className="font-bold">هذا الرابط ليس فيديو مدعومًا</p><p className="max-w-md text-sm text-slate-300">أنهِ الجلسة ثم أضف رابط YouTube أو رابط ملف مباشر ينتهي بـ MP4 أو WebM.</p></div>; }
function VideoSidebar({ session, history }: { session: any; history: any[] }) { const isYoutube = Boolean(youtubeEmbed(session.videoUrl)); return <aside className="space-y-4"><div className="surface p-5"><p className="text-xs font-bold tracking-[.12em] text-primary">وقت المشاهدة النشط</p><p className="mt-2 font-[Manrope] text-4xl font-extrabold">{isYoutube ? "—" : clock(session.activeSeconds)}</p><p className="mt-2 text-sm text-muted-foreground">{isYoutube ? "YouTube يعمل للمشاهدة فقط؛ Coins تحتاج فيديو مباشر." : "كل 45 دقيقة نشطة تفتح دورة راحة جديدة."}</p></div><div className="surface p-5"><div className="mb-4 flex items-center gap-2"><PlayCircle className="size-5 text-primary" /><h2 className="font-bold">دورات مكتملة</h2></div><p className="font-[Manrope] text-3xl font-extrabold">{money.format(session.completedBlocks)}</p><p className="mt-1 text-sm text-muted-foreground">{money.format(session.completedBlocks * 25)} Coins مكتسبة من الفيديو</p></div><div className="surface p-5"><div className="mb-3 flex items-center gap-2"><History className="size-5 text-primary" /><h2 className="font-bold">سجل الجلسات</h2></div>{history.length ? <div className="space-y-3">{history.slice(0, 5).map(item => <div key={item.id} className="flex items-center justify-between text-sm"><span>{clock(item.activeSeconds)} · {item.completedBlocks} دورات</span><span className="text-xs text-muted-foreground">{shortDate.format(new Date(item.updatedAt))}</span></div>)}</div> : <p className="text-sm text-muted-foreground">ستظهر الجلسات هنا بعد البدء.</p>}</div><div className="surface p-5 text-sm leading-6 text-muted-foreground"><Clock3 className="mb-2 size-5 text-primary" />لا تُحتسب قفزات موضع الفيديو غير المنطقية مقارنة بزمن الخادم.</div></aside>; }
