import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "@/components/PageHeader";
import { errorText, money, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { isDirectMedia, youtubeEmbed } from "@/lib/videoSources";
import { CirclePause, CirclePlay, Clock3, Download, ExternalLink, History, Pencil, PlayCircle, Printer, Save, Square, Trash2, Video, XCircle } from "lucide-react";
import { toast } from "sonner";

function clock(seconds: number) { return `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }
function noteTime(seconds: number | null) { return seconds == null ? "بدون توقيت" : `عند ${clock(seconds)}`; }

type VideoNote = { id: number; title: string; content: string; timestampSeconds: number | null; updatedAt: string | Date };
type VideoHistoryItem = { id: number; videoUrl: string; activeSeconds: number; completedBlocks: number; phase: string; updatedAt: string | Date; notes: VideoNote[] };

export default function StudyVideo() {
  const utils = trpc.useUtils(); const { data: session, isLoading } = trpc.video.current.useQuery(); const { data: history = [] } = trpc.video.history.useQuery();
  const [url, setUrl] = useState(""); const [now, setNow] = useState(Date.now()); const [noteTitle, setNoteTitle] = useState(""); const [noteContent, setNoteContent] = useState(""); const [editingNote, setEditingNote] = useState<VideoNote | null>(null); const video = useRef<HTMLVideoElement>(null); const interval = useRef<number | null>(null);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const invalidate = () => Promise.all([utils.video.current.invalidate(), utils.video.history.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.coins.ledger.invalidate()]);
  const start = trpc.video.start.useMutation({ onSuccess: async () => { setUrl(""); toast.success("تم بدء جلسة الفيديو."); await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const end = trpc.video.end.useMutation({ onSuccess: async () => { toast.success("تم إنهاء جلسة الفيديو."); await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const heartbeat = trpc.video.heartbeat.useMutation({ onSuccess: async r => { if (r.blockCompleted) { toast.success("أحسنت! +25 Coins — بدأت استراحة 15 دقيقة."); video.current?.pause(); } await invalidate(); }, onError: e => toast.error(errorText(e)) });
  const resume = trpc.video.resume.useMutation({ onSuccess: async () => { await invalidate(); video.current?.play().catch(() => undefined); }, onError: e => toast.error(errorText(e)) });
  const createNote = trpc.video.createNote.useMutation({ onSuccess: async () => { setNoteTitle(""); setNoteContent(""); toast.success("تم حفظ الملاحظة."); await utils.video.history.invalidate(); }, onError: e => toast.error(errorText(e)) });
  const updateNote = trpc.video.updateNote.useMutation({ onSuccess: async () => { setEditingNote(null); setNoteTitle(""); setNoteContent(""); toast.success("تم تحديث الملاحظة."); await utils.video.history.invalidate(); }, onError: e => toast.error(errorText(e)) });
  const deleteNote = trpc.video.deleteNote.useMutation({ onSuccess: async () => { toast.success("تم حذف الملاحظة."); await utils.video.history.invalidate(); }, onError: e => toast.error(errorText(e)) });
  const send = (active: boolean) => { if (!session) return; heartbeat.mutate({ sessionId: session.id, active, playbackPosition: Math.floor(video.current?.currentTime ?? 0) }); };
  const onPlay = () => { send(true); if (interval.current) clearInterval(interval.current); interval.current = window.setInterval(() => send(true), 60_000); };
  const onPause = () => { if (interval.current) clearInterval(interval.current); interval.current = null; send(false); };
  useEffect(() => () => { if (interval.current) clearInterval(interval.current); }, []);
  const breakRemaining = session?.phase === "break" && session.breakEndsAt ? Math.max(0, Math.ceil((new Date(session.breakEndsAt).getTime() - now) / 1000)) : 0;
  useEffect(() => { if (session?.phase === "break" && breakRemaining === 0 && !resume.isPending) resume.mutate({ sessionId: session.id }); }, [breakRemaining, session?.id, session?.phase]);
  const launch = () => { const clean = url.trim(); if (!youtubeEmbed(clean) && !isDirectMedia(clean)) { toast.error("استخدم رابط YouTube صحيحًا أو رابط ملف فيديو مباشر ينتهي بـ MP4 أو WebM."); return; } start.mutate({ videoUrl: clean }); };
  const saveNote = () => { if ((!session && !editingNote) || !noteTitle.trim() || !noteContent.trim()) return; const timestampSeconds = editingNote ? (session ? Math.floor(video.current?.currentTime ?? editingNote.timestampSeconds ?? 0) : editingNote.timestampSeconds ?? 0) : Math.floor(video.current?.currentTime ?? 0); if (editingNote) updateNote.mutate({ noteId: editingNote.id, title: noteTitle.trim(), content: noteContent.trim(), timestampSeconds }); else createNote.mutate({ sessionId: session!.id, title: noteTitle.trim(), content: noteContent.trim(), timestampSeconds }); };
  const beginEdit = (note: VideoNote) => { setEditingNote(note); setNoteTitle(note.title); setNoteContent(note.content); };
  if (isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-muted" />;
  return <div><PageHeader title="فيديو المذاكرة" description="شاهد الفيديو، وسجّل ملاحظاتك بتوقيت داخل الفيديو. ستجد كل الفيديوهات التي شاهدتها وملاحظاتها في السجل." />
    {!session ? <><div className="surface mx-auto max-w-2xl p-6 sm:p-8"><div className="mb-5 flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Video /></div><h2 className="text-xl font-bold">ابدأ دورة فيديو دراسة</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">الصق رابط YouTube للمشاهدة، أو رابط ملف مباشر ينتهي بـ MP4/WebM للمشاهدة مع احتساب التركيز.</p><div className="mt-6 flex gap-2"><Input dir="ltr" value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === "Enter" && launch()} placeholder="YouTube أو https://example.com/lecture.mp4" /><Button disabled={!url || start.isPending} onClick={launch}>ابدأ</Button></div><p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><ExternalLink className="size-3" />روابط صفحات المواقع أو Drive غير المباشرة لا تعمل داخل المشغّل.</p></div>{editingNote && <div className="mx-auto mt-5 max-w-5xl"><NoteEditor title={noteTitle} content={noteContent} editing onTitle={setNoteTitle} onContent={setNoteContent} onSave={saveNote} onCancel={() => { setEditingNote(null); setNoteTitle(""); setNoteContent(""); }} busy={updateNote.isPending} /></div>}<VideoHistory history={history as VideoHistoryItem[]} onEdit={beginEdit} onDelete={noteId => deleteNote.mutate({ noteId })} /></> : <><div className="grid gap-5 xl:grid-cols-[1fr_.38fr]"><section className="surface overflow-hidden"><Player session={session} video={video} onPlay={onPlay} onPause={onPause} breakRemaining={breakRemaining} onResume={() => resume.mutate({ sessionId: session.id })} /><div className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-semibold">جلسة فيديو نشطة</p><p dir="ltr" className="mt-1 max-w-96 truncate text-xs text-muted-foreground">{session.videoUrl}</p></div><Button size="sm" variant="outline" disabled={end.isPending} onClick={() => end.mutate({ sessionId: session.id })}><Square />إنهاء الجلسة</Button></div></section><VideoSidebar session={session} history={history as VideoHistoryItem[]} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1fr]"><NoteEditor title={noteTitle} content={noteContent} editing={Boolean(editingNote)} onTitle={setNoteTitle} onContent={setNoteContent} onSave={saveNote} onCancel={() => { setEditingNote(null); setNoteTitle(""); setNoteContent(""); }} busy={createNote.isPending || updateNote.isPending} /><VideoHistory history={history as VideoHistoryItem[]} sessionId={session.id} onEdit={beginEdit} onDelete={noteId => deleteNote.mutate({ noteId })} /></div></>}
  </div>;
}

function NoteEditor({ title, content, editing, onTitle, onContent, onSave, onCancel, busy }: { title: string; content: string; editing: boolean; onTitle: (v: string) => void; onContent: (v: string) => void; onSave: () => void; onCancel: () => void; busy: boolean }) { return <section className="surface p-5"><div className="mb-4 flex items-center gap-2"><Pencil className="size-5 text-primary" /><h2 className="font-bold">{editing ? "تعديل الملاحظة" : "ملاحظة جديدة"}</h2></div><Input value={title} onChange={e => onTitle(e.target.value)} placeholder="عنوان الملاحظة" /><Textarea className="mt-3 min-h-32" value={content} onChange={e => onContent(e.target.value)} placeholder="اكتب ما تريد تذكره من الفيديو..." /><p className="mt-2 text-xs text-muted-foreground">سيتم حفظ توقيت التشغيل الحالي تلقائيًا مع الملاحظة.</p><div className="mt-4 flex gap-2"><Button disabled={!title.trim() || !content.trim() || busy} onClick={onSave}><Save />حفظ الملاحظة</Button>{editing && <Button variant="outline" onClick={onCancel}>إلغاء</Button>}</div></section>; }

function safeExportName(url: string) { return (url.match(/(?:v=|youtu\.be\/|\/)([A-Za-z0-9_-]{6,})/)?.[1] ?? "video-notes").slice(0, 48); }
export function formatVideoNotesText(item: VideoHistoryItem) { const lines = [`Seif Study OS — ملاحظات الفيديو`, `الرابط: ${item.videoUrl}`, `تاريخ آخر مشاهدة: ${shortDate.format(new Date(item.updatedAt))}`, `وقت المشاهدة النشط: ${clock(item.activeSeconds)}`, `الدورات المكتملة: ${item.completedBlocks}`, "", ...item.notes.flatMap((note, index) => [`${index + 1}. ${note.title}`, `${noteTime(note.timestampSeconds)} · ${shortDate.format(new Date(note.updatedAt))}`, note.content, ""])]; return lines.join("\\n"); }
function downloadText(item: VideoHistoryItem) { const blob = new Blob(["\\ufeff" + formatVideoNotesText(item)], { type: "text/plain;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${safeExportName(item.videoUrl)}-notes.txt`; link.click(); URL.revokeObjectURL(link.href); toast.success("تم تنزيل الملاحظات كملف نصي."); }
function escapeHtml(value: string) { return value.replace(/[&<>\"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '\"': "&quot;", "'": "&#039;" })[char] ?? char); }
function printPdf(item: VideoHistoryItem) { const popup = window.open("", "_blank", "width=900,height=700"); if (!popup) { toast.error("اسمح بالنوافذ المنبثقة لإنشاء ملف PDF."); return; } const notes = item.notes.map((note, index) => `<article><h2>${index + 1}. ${escapeHtml(note.title)}</h2><p class=meta>${escapeHtml(noteTime(note.timestampSeconds))} · ${escapeHtml(shortDate.format(new Date(note.updatedAt)))}</p><p>${escapeHtml(note.content).replace(/\\n/g, "<br />")}</p></article>`).join(""); popup.document.write(`<!doctype html><html lang=\"ar\" dir=\"rtl\"><head><meta charset=\"utf-8\"><title>ملاحظات الفيديو</title><style>body{font-family:Arial,sans-serif;line-height:1.8;padding:40px;color:#10211d}h1{color:#087f6a;border-bottom:2px solid #bde7dc;padding-bottom:12px}h2{margin-bottom:4px}p{white-space:normal}.meta{color:#60736e;font-size:12px}article{border-bottom:1px solid #d9e4e0;padding:14px 0}@media print{button{display:none}}</style></head><body><h1>ملاحظات الفيديو</h1><p>${escapeHtml(item.videoUrl)}</p><p class=\"meta\">${escapeHtml(shortDate.format(new Date(item.updatedAt)))} · ${clock(item.activeSeconds)} مشاهدة · ${item.completedBlocks} دورات</p>${notes || "<p>لا توجد ملاحظات لهذا الفيديو.</p>"}<button onclick=\"window.print()\">طباعة / حفظ كـ PDF</button></body></html>`); popup.document.close(); popup.focus(); window.setTimeout(() => popup.print(), 300); }

function VideoHistory({ history, sessionId, onEdit, onDelete }: { history: VideoHistoryItem[]; sessionId?: number; onEdit: (note: VideoNote) => void; onDelete: (noteId: number) => void }) { const items = sessionId ? history.filter(item => item.id === sessionId) : history; return <section className="surface mx-auto mt-5 w-full max-w-5xl p-5"><div className="mb-4 flex items-center gap-2"><History className="size-5 text-primary" /><h2 className="font-bold">سجل الفيديوهات والملاحظات</h2></div>{items.length ? <div className="space-y-4">{items.map(item => <article key={item.id} className="rounded-2xl border border-border/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p dir="ltr" className="truncate text-sm font-semibold">{item.videoUrl}</p><p className="mt-1 text-xs text-muted-foreground">{shortDate.format(new Date(item.updatedAt))} · {clock(item.activeSeconds)} مشاهدة · {item.completedBlocks} دورات</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{item.notes.length} ملاحظات</span><Button size="sm" variant="outline" onClick={() => downloadText(item)}><Download className="size-4" />TXT</Button><Button size="sm" variant="outline" onClick={() => printPdf(item)}><Printer className="size-4" />PDF</Button></div></div>{item.notes.length ? <div className="mt-4 space-y-3">{item.notes.map(note => <div key={note.id} className="rounded-xl bg-muted/50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{note.title}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{note.content}</p><p className="mt-2 text-xs text-primary">{noteTime(note.timestampSeconds)} · {shortDate.format(new Date(note.updatedAt))}</p></div><div className="flex shrink-0 gap-1"><Button size="icon" variant="ghost" aria-label="تعديل الملاحظة" onClick={() => onEdit(note)}><Pencil className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="حذف الملاحظة" onClick={() => onDelete(note.id)}><Trash2 className="size-4 text-destructive" /></Button></div></div></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">لا توجد ملاحظات لهذا الفيديو حتى الآن.</p>}</article>)}</div> : <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">ستظهر هنا الفيديوهات التي شاهدتها وملاحظاتها بعد بدء أول جلسة.</div>}</section>; }

function Player({ session, video, onPlay, onPause, breakRemaining, onResume }: { session: any; video: React.RefObject<HTMLVideoElement | null>; onPlay: () => void; onPause: () => void; breakRemaining: number; onResume: () => void }) { const embed = youtubeEmbed(session.videoUrl); if (session.phase === "break") return <div className="relative aspect-video bg-slate-950"><div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center text-white"><CirclePause className="mb-4 size-10 text-amber-300" /><p className="text-sm text-slate-300">فترة استراحة</p><p className="font-[Manrope] text-6xl font-extrabold">{String(Math.floor(breakRemaining / 60)).padStart(2, "0")}:{String(breakRemaining % 60).padStart(2, "0")}</p><Button className="mt-5" onClick={onResume} disabled={breakRemaining > 0}><CirclePlay />استئناف</Button></div></div>; if (embed) return <div className="aspect-video bg-black"><iframe title="فيديو المذاكرة" className="h-full w-full" src={embed} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div>; if (isDirectMedia(session.videoUrl)) return <div className="aspect-video bg-black"><video ref={video} controls className="h-full w-full" src={session.videoUrl} onPlay={onPlay} onPause={onPause} onEnded={onPause}>متصفحك لا يدعم تشغيل الفيديو.</video></div>; return <div className="flex aspect-video flex-col items-center justify-center gap-3 bg-slate-950 p-6 text-center text-white"><XCircle className="size-11 text-rose-300" /><p className="font-bold">هذا الرابط ليس فيديو مدعومًا</p><p className="max-w-md text-sm text-slate-300">أنهِ الجلسة ثم أضف رابط YouTube أو رابط ملف مباشر ينتهي بـ MP4 أو WebM.</p></div>; }

function VideoSidebar({ session, history }: { session: any; history: VideoHistoryItem[] }) { const isYoutube = Boolean(youtubeEmbed(session.videoUrl)); return <aside className="space-y-4"><div className="surface p-5"><p className="text-xs font-bold tracking-[.12em] text-primary">وقت المشاهدة النشط</p><p className="mt-2 font-[Manrope] text-4xl font-extrabold">{isYoutube ? "—" : clock(session.activeSeconds)}</p><p className="mt-2 text-sm text-muted-foreground">{isYoutube ? "YouTube يعمل للمشاهدة فقط؛ Coins تحتاج فيديو مباشر." : "كل 45 دقيقة نشطة تفتح دورة راحة جديدة."}</p></div><div className="surface p-5"><div className="mb-4 flex items-center gap-2"><PlayCircle className="size-5 text-primary" /><h2 className="font-bold">دورات مكتملة</h2></div><p className="font-[Manrope] text-3xl font-extrabold">{money.format(session.completedBlocks)}</p><p className="mt-1 text-sm text-muted-foreground">{money.format(session.completedBlocks * 25)} Coins مكتسبة من الفيديو</p></div><div className="surface p-5 text-sm leading-6 text-muted-foreground"><Clock3 className="mb-2 size-5 text-primary" />لا تُحتسب قفزات موضع الفيديو غير المنطقية مقارنة بزمن الخادم.</div></aside>; }
