import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { completionToast, errorText, money } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { BookOpen, CheckCircle2, ChevronDown, CirclePlus, GraduationCap, Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";

export default function StudyPlan() {
  const utils = trpc.useUtils(); const { data, isLoading } = trpc.studyPlan.list.useQuery();
  const invalidate = () => Promise.all([utils.studyPlan.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate(), utils.achievements.list.invalidate()]);
  if (isLoading) return <div className="h-72 animate-pulse rounded-2xl bg-muted" />;
  const rows = data?.rows ?? []; const subjectMap = new Map<number, any>();
  rows.forEach((row: any) => { if (!subjectMap.has(row.subject.id)) subjectMap.set(row.subject.id, { ...row.subject, chapters: new Map() }); if (row.chapter) { const subject = subjectMap.get(row.subject.id); if (!subject.chapters.has(row.chapter.id)) subject.chapters.set(row.chapter.id, { ...row.chapter, lessons: [] }); if (row.lesson) subject.chapters.get(row.chapter.id).lessons.push({ ...row.lesson, progress: row.progress }); } });
  const subjectList = Array.from(subjectMap.values());
  return <div><PageHeader title="خطة المذاكرة" description="رتب المواد إلى فصول ودروس، ثم دع تقدمك الحقيقي يقود لوحة التحكم." action={{ label: "مادة جديدة", onClick: () => document.getElementById("subject-trigger")?.click() }} /><div className="mb-5 flex flex-wrap gap-2"><CreateSubject onDone={invalidate} /><CreateChapter subjects={subjectList} onDone={invalidate} /><CreateLesson subjects={subjectList} onDone={invalidate} /></div>{!subjectMap.size ? <EmptyState title="ابدأ ببناء خطتك" description="أنشئ مادة، ثم فصلًا ودروسًا قابلة للقياس. لا تمنح الإضافة Coins؛ المكافأة تأتي من إكمال العمل الحقيقي." /> : <div className="space-y-4">{subjectList.map((subject: any) => <div key={subject.id} className="surface overflow-hidden"><div className="flex items-center gap-3 border-b px-5 py-4"><span className="size-3 rounded-full" style={{ backgroundColor: subject.color }} /><div className="flex-1"><h2 className="font-bold">{subject.title}</h2><p className="text-xs text-muted-foreground">{subject.chapters.size} فصل</p></div><Badge variant="secondary"><BookOpen className="ml-1 size-3" />مادة</Badge><ResourceActions kind="subject" item={subject} onDone={invalidate} /></div>{Array.from(subject.chapters.values()).map((chapter: any) => <div key={chapter.id} className="border-b last:border-0"><div className="flex items-center gap-2 bg-muted/35 px-5 py-3 text-sm font-semibold"><ChevronDown className="size-4 text-muted-foreground" />{chapter.title}<span className="mr-auto text-xs font-normal text-muted-foreground">{chapter.lessons.length} دروس</span><ResourceActions kind="chapter" item={chapter} onDone={invalidate} /></div><div className="divide-y">{chapter.lessons.map((lesson: any) => <LessonRow key={lesson.id} lesson={lesson} onDone={invalidate} />)}{!chapter.lessons.length && <p className="px-5 py-4 text-sm text-muted-foreground">لا توجد دروس في هذا الفصل بعد.</p>}</div></div>)}</div>)}</div>}</div>;
}
function LessonRow({ lesson, onDone }: { lesson: any; onDone: () => Promise<any> }) { const [busy, setBusy] = useState(false); const complete = trpc.studyPlan.complete.useMutation({ onSuccess: async r => { completionToast(r, 75); await onDone(); }, onError: e => toast.error(errorText(e)) }); const review = trpc.studyPlan.review.useMutation({ onSuccess: async r => { completionToast(r, 15); await onDone(); }, onError: e => toast.error(errorText(e)) }); const p = lesson.progress; const status = p?.status ?? "not_started"; return <div className="px-5 py-4"><div className="flex flex-wrap items-center gap-3"><span className={`flex size-8 items-center justify-center rounded-lg ${status === "completed" ? "bg-emerald-100 text-emerald-700" : "bg-secondary text-primary"}`}>{status === "completed" ? <CheckCircle2 className="size-4" /> : <GraduationCap className="size-4" />}</span><div className="min-w-48 flex-1"><p className="text-sm font-semibold">{lesson.title}</p><p className="text-xs text-muted-foreground">{money.format(lesson.estimatedMinutes)} دقيقة · {lesson.description || "بدون وصف"}</p></div><Badge variant={status === "completed" ? "default" : "secondary"}>{status === "completed" ? "مكتمل" : status === "in_progress" ? "قيد الدراسة" : "لم يبدأ"}</Badge>{status === "completed" ? <Button size="sm" variant="outline" disabled={review.isPending} onClick={() => review.mutate({ lessonId: lesson.id })}><RefreshCw className="size-3.5" />مراجعة +15</Button> : <Button size="sm" disabled={complete.isPending || busy} onClick={() => { setBusy(true); complete.mutate({ lessonId: lesson.id }, { onSettled: () => setBusy(false) }); }}><CheckCircle2 className="size-3.5" />إكمال +75</Button>}<ResourceActions kind="lesson" item={lesson} onDone={onDone} /></div><div className="mr-11 mt-3"><Progress value={p?.progress ?? 0} className="h-1.5" /></div></div>; }
function ResourceActions({ kind, item, onDone }: { kind: "subject" | "chapter" | "lesson"; item: any; onDone: () => Promise<any> }) { const updateSubject = trpc.studyPlan.updateSubject.useMutation({ onSuccess: async () => { toast.success("تم التحديث."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const updateChapter = trpc.studyPlan.updateChapter.useMutation({ onSuccess: async () => { toast.success("تم التحديث."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const updateLesson = trpc.studyPlan.updateLesson.useMutation({ onSuccess: async () => { toast.success("تم التحديث."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const deleteSubject = trpc.studyPlan.deleteSubject.useMutation({ onSuccess: async () => { toast.success("تم الحذف."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const deleteChapter = trpc.studyPlan.deleteChapter.useMutation({ onSuccess: async () => { toast.success("تم الحذف."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const deleteLesson = trpc.studyPlan.deleteLesson.useMutation({ onSuccess: async () => { toast.success("تم الحذف."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const edit = () => { const title = window.prompt("العنوان", item.title); if (!title?.trim()) return; if (kind === "subject") updateSubject.mutate({ subjectId: item.id, title, color: item.color }); if (kind === "chapter") updateChapter.mutate({ chapterId: item.id, title }); if (kind === "lesson") updateLesson.mutate({ lessonId: item.id, title, description: item.description ?? undefined, estimatedMinutes: item.estimatedMinutes, notes: item.notes ?? undefined }); }; const remove = () => { if (!window.confirm("سيتم حذف هذا العنصر وكل ما يرتبط به. هل تريد المتابعة؟")) return; if (kind === "subject") deleteSubject.mutate({ subjectId: item.id }); if (kind === "chapter") deleteChapter.mutate({ chapterId: item.id }); if (kind === "lesson") deleteLesson.mutate({ lessonId: item.id }); }; return <span className="flex gap-1"><Button size="icon" variant="ghost" className="size-7" aria-label="تعديل" onClick={edit}><Pencil className="size-3.5" /></Button><Button size="icon" variant="ghost" className="size-7" aria-label="حذف" onClick={remove}><Trash2 className="size-3.5 text-rose-600" /></Button></span>; }
function CreateSubject({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const mutation = trpc.studyPlan.createSubject.useMutation({ onSuccess: async () => { toast.success("تمت إضافة المادة."); setOpen(false); setTitle(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="subject-trigger" asChild><Button><Plus />مادة جديدة</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>إضافة مادة</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="مثال: الرياضيات" /><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title })}>حفظ</Button></DialogFooter></DialogContent></Dialog>; }
function CreateChapter({ subjects, onDone }: { subjects: any[]; onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [subjectId, setSubjectId] = useState(""), [title, setTitle] = useState(""); const mutation = trpc.studyPlan.createChapter.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الفصل."); setOpen(false); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" disabled={!subjects.length}><CirclePlus />فصل</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>إضافة فصل</DialogTitle></DialogHeader><select value={subjectId} onChange={e => setSubjectId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="">اختر المادة</option>{subjects.map(x => <option key={x.id} value={x.id}>{x.title}</option>)}</select><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="اسم الفصل" /><DialogFooter><Button disabled={!subjectId || !title.trim() || mutation.isPending} onClick={() => mutation.mutate({ subjectId: Number(subjectId), title })}>حفظ</Button></DialogFooter></DialogContent></Dialog>; }
function CreateLesson({ subjects, onDone }: { subjects: any[]; onDone: () => Promise<any> }) { const chapters = subjects.flatMap(s => Array.from(s.chapters.values()).map((c: any) => ({ ...c, subject: s.title }))); const [open, setOpen] = useState(false), [chapterId, setChapterId] = useState(""), [title, setTitle] = useState(""), [description, setDescription] = useState(""), [minutes, setMinutes] = useState("30"); const mutation = trpc.studyPlan.createLesson.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الدرس."); setOpen(false); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" disabled={!chapters.length}><CirclePlus />درس</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>إضافة درس</DialogTitle></DialogHeader><select value={chapterId} onChange={e => setChapterId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="">اختر الفصل</option>{chapters.map(x => <option key={x.id} value={x.id}>{x.subject} — {x.title}</option>)}</select><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="عنوان الدرس" /><Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="وصف مختصر (اختياري)" /><Input type="number" min="5" value={minutes} onChange={e => setMinutes(e.target.value)} placeholder="المدة بالدقائق" /><DialogFooter><Button disabled={!chapterId || !title.trim() || mutation.isPending} onClick={() => mutation.mutate({ chapterId: Number(chapterId), title, description: description || undefined, estimatedMinutes: Number(minutes) || 30 })}>حفظ</Button></DialogFooter></DialogContent></Dialog>; }
