import { useState } from "react";
import { Input } from "@/components/ui/input";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { BookOpen, Layers3, NotebookPen, Search } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function StudySearch() { const [query, setQuery] = useState(""); const enabled = query.trim().length > 1; const { data, isFetching } = trpc.studySearch.query.useQuery({ query: query.trim() }, { enabled }); const total = (data?.notes.length ?? 0) + (data?.lessons.length ?? 0) + (data?.flashcards.length ?? 0); return <div><PageHeader title="دوّر في مذاكرتك" description="ابحث جوه نوتاتك ودروسك وفلاش كاردزك، من غير ما تضيع بين تبويبات كتير." /><div className="surface p-5"><div className="flex gap-2"><Input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="اكتب كلمة، تعريف، قانون، أو اسم درس..." onKeyDown={event => event.key === "Enter" && event.currentTarget.blur()} /><Button disabled={!enabled}><Search />دوّر</Button></div><p className="mt-3 text-xs text-muted-foreground">البحث بيتم في المحتوى اللي أنت كتبته جوه Study OS فقط.</p></div>{enabled && <div className="mt-5">{isFetching ? <div className="h-44 animate-pulse rounded-2xl bg-muted" /> : total ? <div className="grid gap-4 lg:grid-cols-3"><Results icon={NotebookPen} title="النوتس" items={data?.notes ?? []} render={item => <><b>{item.title}</b><p>{item.excerpt.slice(0, 140)}</p><small>{item.notebook}</small></>} /><Results icon={BookOpen} title="الدروس" items={data?.lessons ?? []} render={item => <><b>{item.title}</b><p>{item.excerpt?.slice(0, 140) || "درس من خطتك"}</p><small>{item.subject} · {item.chapter}</small></>} /><Results icon={Layers3} title="الفلاش كاردز" items={data?.flashcards ?? []} render={item => <><b>{item.prompt}</b><p>{item.answer.slice(0, 140)}</p><small>{item.deck}</small></>} /></div> : <EmptyState title="ملقيناش حاجة بالكلمة دي" description="جرّب كلمة أبسط، أو أضف نوتس ودروس وفلاش كاردز أكتر." />}</div>}</div>; }
function Results({ icon: Icon, title, items, render }: { icon: any; title: string; items: any[]; render: (item: any) => React.ReactNode }) { return <section className="surface p-5"><div className="mb-4 flex items-center gap-2"><Icon className="size-5 text-primary" /><h2 className="font-bold">{title}</h2><span className="mr-auto rounded-full bg-muted px-2 py-1 text-xs">{items.length}</span></div>{items.length ? <div className="space-y-3">{items.map(item => <article key={item.id} className="rounded-xl bg-muted/55 p-3 text-sm [&>p]:mt-1 [&>p]:text-muted-foreground [&>small]:mt-2 [&>small]:block [&>small]:text-xs [&>small]:text-primary">{render(item)}</article>)}</div> : <p className="text-sm text-muted-foreground">مفيش نتائج من النوع ده.</p>}</section>; }
