import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { PageHeader, EmptyState } from "@/components/PageHeader";
import { completionToast, errorText, inputDate, shortDate } from "@/lib/study";
import { trpc } from "@/lib/trpc";
import { CalendarDays, CheckCircle2, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";

const priorityMap: any = { urgent: ["عاجل", "bg-rose-100 text-rose-700"], medium: ["متوسط", "bg-amber-100 text-amber-800"], low: ["منخفض", "bg-emerald-100 text-emerald-700"] };
export default function Tasks() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.tasks.list.useQuery(); const invalidate = () => Promise.all([utils.tasks.list.invalidate(), utils.dashboard.summary.invalidate(), utils.analytics.overview.invalidate()]); if (isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-muted" />; return <div><PageHeader title="الجدول اليومي" description="مهامك محفوظة في قاعدة البيانات. الإضافة والتعديل لا يمنحان Coins؛ الإكمال فقط هو الذي يُكافأ." action={{ label: "مهمة جديدة", onClick: () => document.getElementById("task-trigger")?.click() }} /><CreateTask onDone={invalidate} />{!data?.length ? <EmptyState title="اليوم متاح لك" description="أضف أول مهمة، حدّد أولوية واضحة، ثم أكملها عند إنجاز العمل الحقيقي." /> : <div className="surface divide-y overflow-hidden">{data.map(task => <TaskRow key={task.id} task={task} onDone={invalidate} />)}</div>}</div>; }
function TaskRow({ task, onDone }: { task: any; onDone: () => Promise<any> }) { const mutation = trpc.tasks.complete.useMutation({ onSuccess: async r => { completionToast(r, task.priority === "urgent" ? 30 : task.priority === "medium" ? 20 : 10); await onDone(); }, onError: e => toast.error(errorText(e)) }); const remove = trpc.tasks.delete.useMutation({ onSuccess: async () => { toast.success("تم حذف المهمة."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const edit = trpc.tasks.update.useMutation({ onSuccess: async () => { toast.success("تم تحديث المهمة."); await onDone(); }, onError: e => toast.error(errorText(e)) }); const [label, tone] = priorityMap[task.priority]; const updateTitle = () => { const title = window.prompt("عنوان المهمة", task.title); if (title?.trim()) edit.mutate({ taskId: task.id, title, description: task.description ?? undefined, scheduledFor: task.scheduledFor ?? undefined, deadline: task.deadline ? new Date(task.deadline) : undefined, priority: task.priority, category: task.category }); }; return <div className="flex items-center gap-4 p-4 sm:p-5"><Checkbox checked={task.status === "completed"} disabled={task.status === "completed" || mutation.isPending} onCheckedChange={() => mutation.mutate({ taskId: task.id })} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`font-semibold ${task.status === "completed" ? "text-muted-foreground line-through" : ""}`}>{task.title}</p><Badge className={tone}>{label}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{task.description || task.category} {task.deadline && <>· آخر موعد {shortDate.format(new Date(task.deadline))}</>}</p></div><div className="hidden text-left text-xs text-muted-foreground sm:block"><CalendarDays className="mr-auto mb-1 size-4" />{task.scheduledFor ? shortDate.format(new Date(`${task.scheduledFor}T00:00:00`)) : "غير مجدولة"}</div><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="تعديل المهمة" onClick={updateTitle}><Pencil className="size-4" /></Button><Button size="icon" variant="ghost" aria-label="حذف المهمة" disabled={remove.isPending} onClick={() => window.confirm("حذف هذه المهمة؟") && remove.mutate({ taskId: task.id })}><Trash2 className="size-4 text-rose-600" /></Button></div></div>; }
function CreateTask({ onDone }: { onDone: () => Promise<any> }) { const [open, setOpen] = useState(false), [title, setTitle] = useState(""), [desc, setDesc] = useState(""), [date, setDate] = useState(inputDate(new Date())), [priority, setPriority] = useState<"urgent" | "medium" | "low">("medium"); const mutation = trpc.tasks.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة المهمة."); setOpen(false); setTitle(""); setDesc(""); await onDone(); }, onError: e => toast.error(errorText(e)) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger id="task-trigger" asChild><span /></DialogTrigger><DialogContent><DialogHeader><DialogTitle>مهمة جديدة</DialogTitle></DialogHeader><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="ما الخطوة التي ستنجزها؟" /><Textarea value={desc} onChange={e => setDesc(e.target.value)} placeholder="تفاصيل اختيارية" /><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={date} onChange={e => setDate(e.target.value)} /><select value={priority} onChange={e => setPriority(e.target.value as any)} className="h-10 rounded-md border bg-background px-3"><option value="urgent">عاجل · +30</option><option value="medium">متوسط · +20</option><option value="low">منخفض · +10</option></select></div><DialogFooter><Button disabled={!title.trim() || mutation.isPending} onClick={() => mutation.mutate({ title, description: desc || undefined, scheduledFor: date, priority })}><Plus />إضافة المهمة</Button></DialogFooter></DialogContent></Dialog>; }
